import pygame

WINDOW_WIDTH = 800
WINDOW_HEIGHT = 800

SPAWN_THRASH_EVENT = pygame.USEREVENT + 1
GAME_OVER_EVENT = pygame.USEREVENT + 2
THRASH_MAX_SPEED = 4
THRASH_DT_MULTIPLIER = 0.75
THRASH_SPAWN_MS_DELAY = 1000

PLAYER_X_SPAWN_POINT = 350
PLAYER_Y_SPAWN_POINT = 350
PLAYER_MAX_SPEED = 7
PLAYER_DT_MULTIPLIER = 2
